drop table TASKS;
CREATE TABLE TASKS (
    ID NUMBER(38) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    QUEUE_NAME varchar(50) NOT NULL,
    STATUS varchar(30),
    PAYLOAD CLOB,
    REFERENCE_NUMBER varchar(100),
    CREATE_TIME        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    NEXT_PROCESS_TIME   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATE_TIME   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IDX_TASKS_NAME_TIME
  ON TASKS (QUEUE_NAME, NEXT_PROCESS_TIME, ID DESC);


select * FROM tasks;
--truncate table TASKS;
--insert into TASKS (ID, STATUS, INSTANCE, CREATE_TIME) values (1, 'CREATED', 'B', 1677337372696);
--insert into TASKS (ID, STATUS, INSTANCE, CREATE_TIME) values (2, 'CREATED', 'B', 1677337372697);
--insert into TASKS (ID, STATUS, INSTANCE, CREATE_TIME) values (3, 'CREATED', 'B', 1677337372698);
--insert into TASKS (ID, STATUS, INSTANCE, CREATE_TIME) values (4, 'CREATED', 'B', 1677337372699);
--COMMIT;
--
--SELECT * FROM PAYMENT where status = 'CHECKED' AND ID % 5 = 1;
--
--
--select count(*) from payment;
--
--SELECT * FROM PAYMENT;
--
--delete  from payment when status = 'CREATED';