{
 "title": "Task Queue",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Task Queue Process Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_queue $tag_result",
     "expr": "sum(rate(vertx_eventbus_sent_total[1m]))",
     "groupBy": [
      { "params": [ "queue::tag" ], "type": "tag" },
      { "params": [ "result::tag" ], "type": "tag" }
     ],
     "legendFormat": "Average",
     "measurement": "taskqueue_taskprocessor",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Task Queue Process Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_queue $tag_result",
     "expr": "sum(irate(vertx_eventbus_processingTime_seconds_sum[1m])) / sum(irate(vertx_eventbus_processingTime_seconds_count[1m]))",
     "groupBy": [
      { "params": [ "queue::tag" ], "type": "tag" },
      { "params": [ "result::tag" ], "type": "tag" }
     ],
     "legendFormat": "Average",
     "measurement": "taskqueue_taskprocessor",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Task Queue Poller Fetch Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_queue $tag_result",
     "expr": "sum(rate(vertx_eventbus_sent_total[1m]))",
     "groupBy": [
      { "params": [ "queue::tag" ], "type": "tag" },
      { "params": [ "result::tag" ], "type": "tag" }
     ],
     "legendFormat": "Average",
     "measurement": "taskqueue_poller_fetch",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Task Queue Poller Fetch Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_queue $tag_result",
     "expr": "sum(irate(vertx_eventbus_processingTime_seconds_sum[1m])) / sum(irate(vertx_eventbus_processingTime_seconds_count[1m]))",
     "groupBy": [
      { "params": [ "queue::tag" ], "type": "tag" },
      { "params": [ "result::tag" ], "type": "tag" }
     ],
     "legendFormat": "Average",
     "measurement": "taskqueue_poller_fetch",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Task Queue Process Batch Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_queue $tag_result",
     "expr": "sum(rate(vertx_eventbus_sent_total[1m]))",
     "groupBy": [
      { "params": [ "queue::tag" ], "type": "tag" },
      { "params": [ "result::tag" ], "type": "tag" }
     ],
     "legendFormat": "Average",
     "measurement": "taskqueue_poller_process_batch",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Task Queue Process Batch Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_queue $tag_result",
     "expr": "sum(irate(vertx_eventbus_processingTime_seconds_sum[1m])) / sum(irate(vertx_eventbus_processingTime_seconds_count[1m]))",
     "groupBy": [
      { "params": [ "queue::tag" ], "type": "tag" },
      { "params": [ "result::tag" ], "type": "tag" }
     ],
     "legendFormat": "Average",
     "measurement": "taskqueue_poller_process_batch",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Task Queue Process Single Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_queue $tag_result",
     "expr": "sum(rate(vertx_eventbus_sent_total[1m]))",
     "groupBy": [
      { "params": [ "queue::tag" ], "type": "tag" },
      { "params": [ "result::tag" ], "type": "tag" }
     ],
     "legendFormat": "Average",
     "measurement": "taskqueue_poller_process_single",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Task Queue Process Single Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_queue $tag_result",
     "expr": "sum(irate(vertx_eventbus_processingTime_seconds_sum[1m])) / sum(irate(vertx_eventbus_processingTime_seconds_count[1m]))",
     "groupBy": [
      { "params": [ "queue::tag" ], "type": "tag" },
      { "params": [ "result::tag" ], "type": "tag" }
     ],
     "legendFormat": "Average",
     "measurement": "taskqueue_poller_process_single",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vertx_http_server_connections",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "legendFormat": "{{local}}",
     "measurement": "vertx_http_server_connections",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request count rate by error code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(_total[1m])) by (code), 0.001)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "code" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vertx_http_server_requestCount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request count rate by code and path",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(_total[1m])) by (local,code,path), 0.001)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "local" ], "type": "tag" },
      { "params": [ "code" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vertx_http_server_requestCount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(irate(_seconds_sum[1m])) / sum(irate(vertx_http_server_responseTime_seconds_count[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "legendFormat": "Average",
     "measurement": "vertx_http_server_responseTime",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average response time by path",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_http_server_responseTime_seconds_sum[1m])) by (path) / sum(irate(vertx_http_server_responseTime_seconds_count[1m])) by (path)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vertx_http_server_responseTime",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Server bytes sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vertx_http_server_bytesSent_sum[1m])) / sum(rate(vertx_http_server_bytesSent_count[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "legendFormat": "sent",
     "measurement": "vertx_http_server_bytesSent",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Server bytes received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vertx_http_server_bytesReceived_sum[1m])) / sum(rate(vertx_http_server_bytesReceived_count[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "legendFormat": "received",
     "measurement": "vertx_http_server_bytesReceived",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Eventbus: handlers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vertx_eventbus_handlers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "address" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "legendFormat": "{{address}}",
     "measurement": "vertx_eventbus_handlers",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Eventbus: pending",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "legendFormat": "{{address}}",
     "measurement": "vertx_eventbus_pending",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Eventbus: pending",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "legendFormat": "{{address}}",
     "measurement": "vertx_eventbus_pending",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Eventbus: received ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 49 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vertx_eventbus_received_total[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "legendFormat": "Average",
     "measurement": "vertx_eventbus_received",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Eventbus processing time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_processingTime_seconds_sum[1m])) / sum(irate(vertx_eventbus_processingTime_seconds_count[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "legendFormat": "Average",
     "measurement": "vertx_eventbus_processingTime",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Eventbus processing time by address",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_processingTime_seconds_sum[1m])) by (address) / sum(irate(vertx_eventbus_processingTime_seconds_count[1m])) by (address)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "address" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vertx_eventbus_processingTime",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}