package io.github.colinzhu.taskqueue;

import io.vertx.core.Future;
import io.vertx.core.Vertx;
import io.vertx.core.json.JsonObject;
import io.vertx.jdbcclient.JDBCPool;
import io.vertx.sqlclient.Row;
import io.vertx.sqlclient.RowSet;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.h2.tools.Server;

@Slf4j
@RequiredArgsConstructor
public class H2Database implements Database {
    private final boolean isMemoryDb;

    public static void main(String[] args) {
        new H2Database(false).startServer();
    }
    @Override
    public void startServer() {
        try {
            Server.createTcpServer("-tcpPort", "9092", "-tcpAllowOthers", "-ifNotExists", "-baseDir", "./").start();
            log.info("H2 database TCP server created at default port (9092). jdbc:h2:tcp://localhost/example-db");
            Server.createWebServer("-webPort", "9091").start();
            log.info("H2 database WEB server created at 9091 port. http://localhost:9091/");
        } catch (Exception e) {
            log.warn("Seems servers already started.", e);
        }
    }

    @Override
    public JDBCPool getJdbcPool(Vertx vertx) {
        String url;
        if (!isMemoryDb) {
            url = "jdbc:h2:tcp://localhost/example-db;MODE=Oracle;DEFAULT_NULL_ORDERING=HIGH";
        } else {
            url = "jdbc:h2:mem:taskqueuetest;MODE=Oracle;DEFAULT_NULL_ORDERING=HIGH";
        }
        final JsonObject config = new JsonObject()
                .put("url", url)
                .put("driver_class", "org.h2.Driver")
                .put("datasourceName", "example-db")
                .put("user", "sa")
                .put("password", "sa")
                .put("max_pool_size", 50);
        return JDBCPool.pool(vertx, config);
    }

    @Override
    public Future<?> createTables(JDBCPool pool) {
        Future<?> f1 = H2Database.createPaymentTable(pool);
        Future<?> f2 = H2Database.createTaskTable(pool);
        return Future.join(f1, f2);
    }

    private static Future<RowSet<Row>> createTaskTable(JDBCPool pool) {
        String sql = """
DROP TABLE IF EXISTS TASKS;
CREATE TABLE TASKS (
  ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
  QUEUE_NAME VARCHAR2(200) NOT NULL,
  REFERENCE_NUMBER VARCHAR2(200),
  STATUS VARCHAR2(30),
  ATTEMPT NUMBER DEFAULT 0,
  PAYLOAD CLOB,
  PROCESS_RESULT VARCHAR2(4000),
  CREATE_TIME TIMESTAMP with TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  NEXT_PROCESS_TIME   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  LAST_UPDATE_TIME   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IDX_QNAME_NEXT_PROC_TIME ON TASKS(QUEUE_NAME, NEXT_PROCESS_TIME);
                """;
        return pool.query(sql).execute()
                .onSuccess(result -> log.info("TASK TABLE CREATED"))
                .onFailure(err -> log.error("Fail to create TASKS table", err));
    }


    private static Future<RowSet<Row>> createPaymentTable(JDBCPool pool) {
        String sql = """
DROP TABLE IF EXISTS PAYMENT;
CREATE TABLE PAYMENT (
  ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
  STATUS VARCHAR2(30),
  CREATE_TIME TIMESTAMP WITH TIME ZONE
);
                """;
        return pool.query(sql).execute()
                .onSuccess(result -> log.info("PAYMENT TABLE CREATED"))
                .onFailure(err -> log.error("Fail to create PAYMENT table", err));
    }

}
