package io.github.colinzhu.taskqueue;

import io.vertx.core.Future;
import io.vertx.core.Vertx;
import io.vertx.core.json.JsonObject;
import io.vertx.jdbcclient.JDBCPool;
import io.vertx.sqlclient.Row;
import io.vertx.sqlclient.RowSet;
import lombok.extern.slf4j.Slf4j;
import org.h2.tools.Server;

@Slf4j
public class H2Database {
    public static void main(String... args) {
        createH2Server();
    }

    public static void createH2Server() {
        try {
            Server.createTcpServer("-tcpPort", "9092", "-tcpAllowOthers", "-ifNotExists", "-baseDir", "./").start();
            log.info("H2 database TCP server created at default port (9092). jdbc:h2:tcp://localhost/example-db");
            Server.createWebServer("-webPort", "9091").start();
            log.info("H2 database WEB server created at 9091 port. http://localhost:9091/");
        } catch (Exception e) {
            log.warn("Seems servers already started.", e);
        }
    }

    public static Future<?> createTables(JDBCPool pool) {
        Future<?> f1 = H2Database.createPaymentTable(pool);
        Future<?> f2 = H2Database.createTaskTable(pool);
        return Future.join(f1, f2);
    }

    public static JDBCPool getJdbcPool(Vertx vertx, boolean isMemoryDb) {
        String url;
        if (!isMemoryDb) {
            url = "jdbc:h2:tcp://localhost/example-db;MODE=Oracle;DEFAULT_NULL_ORDERING=HIGH";
        } else {
            url = "jdbc:h2:mem:taskqueuetest;MODE=Oracle;DEFAULT_NULL_ORDERING=HIGH";
        }
        final JsonObject config = new JsonObject()
                .put("url", url)
                .put("driver_class", "org.h2.Driver")
                .put("datasourceName", "example-db")
                .put("user", "sa")
                .put("password", "sa")
                .put("max_pool_size", 20);
        return JDBCPool.pool(vertx, config);
    }

    private static Future<RowSet<Row>> createTaskTable(JDBCPool pool) {
        String sqlH2 = """
                drop table TASKS IF EXISTS;
                create table IF NOT EXISTS TASKS (
                    ID bigint auto_increment,
                    QUEUE_NAME varchar2(50) NOT NULL,
                    ATTEMPT bigint DEFAULT 0,
                    STATUS varchar2(30),
                    PAYLOAD CLOB,
                    REFERENCE_NUMBER varchar(100),
                    CREATE_TIME TIMESTAMP with TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                    NEXT_PROCESS_TIME   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                    LAST_UPDATE_TIME   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
                );
                """;
        String sqlOracle = """
DROP TABLE IF EXISTS TASKS;
CREATE TABLE TASKS (
  ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
  QUEUE_NAME VARCHAR2(200) NOT NULL,
  REFERENCE_NUMBER VARCHAR2(200),
  STATUS VARCHAR2(30),
  ATTEMPT NUMBER DEFAULT 0,
  PAYLOAD CLOB,
  CREATE_TIME TIMESTAMP with TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  NEXT_PROCESS_TIME   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  LAST_UPDATE_TIME   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IDX_QNAME_NEXT_PROC_TIME ON TASKS(QUEUE_NAME, NEXT_PROCESS_TIME);
                """;
        return pool.query(sqlOracle).execute()
                .onSuccess(result -> log.info("TASK TABLE CREATED"))
                .onFailure(err -> log.error("Fail to create TASKS table", err));
    }


    private static Future<RowSet<Row>> createPaymentTable(JDBCPool pool) {
        String sqlH2 = """
                drop table payment IF EXISTS;
                create table IF NOT EXISTS PAYMENT (
                    ID bigint auto_increment,
                    STATUS varchar(30),
                    CREATE_TIME bigint,
                    PRIMARY KEY (ID)
                );
                """;
        String sqlOracle = """
DROP TABLE IF EXISTS PAYMENT;
CREATE TABLE PAYMENT (
  ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
  STATUS VARCHAR2(30),
  CREATE_TIME TIMESTAMP WITH TIME ZONE
);
                """;
        return pool.query(sqlOracle).execute()
                .onSuccess(result -> log.info("PAYMENT TABLE CREATED"))
                .onFailure(err -> log.error("Fail to create PAYMENT table", err));
    }

}
